services:
  shared-frontend:
    build: ./shared
    image: journeybuddy-shared
    container_name: shared-frontend
    volumes:
      - shared-data:/app/instance
    ports:
      - "8080:80"
    networks:
      - journeybuddy-net
    depends_on:
      - student-AlvindhoEdlyn
      - student-KeyuanGan
      - student-RenzoRobin
      - student-TrongDao
      - student-YajunNing
  student-AlvindhoEdlyn:
    build: ./student-AlvindhoEdlyn
    image: journeybuddy-student-alvindhoedlyn
    container_name: student-AlvindhoEdlyn-app
    ports:
      - "5001:5000"
    volumes:
      - alvindhoedlyn-data:/app/instance
    environment:
      - OLLAMA_BASE_URL=http://ai-mode:11434
    networks:
      - journeybuddy-net
    depends_on:
      - ai-mode

  student-KeyuanGan:
    build: ./student-KeyuanGan
    image: journeybuddy-student-keyuangan
    container_name: student-KeyuanGan-app
    ports:
      - "5002:5000"
    volumes:
      - keyuangan-data:/app/instance
    environment:
      - OLLAMA_BASE_URL=http://ai-mode:11434
    networks:
      - journeybuddy-net
    depends_on:
      - ai-mode

  student-RenzoRobin:
    build: ./student-RenzoRobin
    image: journeybuddy-student-renzorobin
    container_name: student-RenzoRobin-app
    ports:
      - "5003:5000"
    volumes:
      - renzorobin-data:/app/instance
    environment:
      - OLLAMA_BASE_URL=http://ai-mode:11434
    networks:
      - journeybuddy-net
    depends_on:
      - ai-mode

  student-TrongDao:
    build: ./student-TrongDao
    image: journeybuddy-student-trongdao
    container_name: student-TrongDao-app
    ports:
      - "5004:5000"
    volumes:
      - trongdao-data:/app/instance
    environment:
      - OLLAMA_BASE_URL=http://ai-mode:11434
    networks:
      - journeybuddy-net
    depends_on:
      - ai-mode

  student-YajunNing:
    build: ./student-YajunNing
    image: journeybuddy-student-yajunning
    container_name: student-YajunNing-app
    ports:
      - "5005:5000"
    volumes:
      - yajunning-data:/app/instance
    environment:
      - OLLAMA_BASE_URL=http://ai-mode:11434
    networks:
      - journeybuddy-net
    depends_on:
      - ai-mode
  ai-mode:
    image: ollama/ollama:latest
    container_name: ai-mode
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    networks:
      - journeybuddy-net

networks:
  journeybuddy-net:
    driver: bridge

volumes:
  ollama-models:
  shared-data:
  alvindhoedlyn-data:
  keyuangan-data:
  renzorobin-data:
  trongdao-data:
  yajunning-data:
