server {
    listen 80;
    include /etc/nginx/mime.types;
    root /usr/share/nginx/html;

    # Root / Itinerary page
    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Explicit route for MCP Panel
    location /mcp_frontend {
        try_files /mcp_frontend.html =404;
    }

    # Explicit route for RAG Assistant
    location /rag_frontend {
        try_files /rag_frontend.html =404;
    }

    # Preserves /api/ in the requested path sent to the backend container
    location /api/ {
        proxy_pass http://student-AlvindhoEdlyn:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ask-with-context {
        proxy_pass http://student-AlvindhoEdlyn:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Preserves /mcp/ in the requested path sent to the backend container
    location /mcp/ {
        proxy_pass http://student-AlvindhoEdlyn:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}